export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const UPDATE_CUSTOMER = "REMOVE_CUSTOMER";

export const GET_USERS = "GET_USERS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const GET_ALL_ORG_USERS_SUCCESS = "GET_ALL_ORG_USERS_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const CREATE_COURSE = "CREATE_COURSE";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
