export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const UPDATE_CUSTOMER = "REMOVE_CUSTOMER";

export const CREATE_USER = "CREATE_USER";
export const GET_USERS = "GET_USERS";
export const GET_ALL_ORG_USERS = "GET_ALL_ORG_USERS";

export const CREATE_COURSE = "CREATE_COURSE";
